Add custom HTTP headers to fetchers to allow resource time-based negotiation
pietercolpaert/ldfetch pull request #2
Opened 2017-08-21 15:22 UTC by julianrojas87

2017-08-21 16:50 UTC, pietercolpaert requested changes
Thanks! 2 minor comments

2017-08-21 16:50 UTC, pietercolpaert commented on lib/BrowserHttpFetcher.js
> +function HttpFetcher(accept, customHeaders, maxParallel) {
This will break backwards compatibility. Can we add the customHeaders as the last parameter? We should then check whether maxParallel is an integer or not, and if it appears not to be an integer, it will be the customHeaders parameter. This  way, we have a good backwards compatible strategy I guess...

2017-08-21 16:50 UTC, pietercolpaert commented on lib/NodeHttpFetcher.js
> +function HttpFetcher(accept, customHeaders, maxParallel, enableCache) {
Same comment here: we want backwards compatibility, so I’d add it at the end

2017-08-22 10:46 UTC, julianrojas87 commented
Changes are impemented.

2017-08-22 13:33 UTC, pietercolpaert commented
Blocked until backwards compatibility is tested

2017-08-23 09:38 UTC, pietercolpaert commented on README.md
> +var options = {headers: [{key: 'Accept-Datetime', value: '2017-03-11T17:00:00.000Z'}]}; // optional
Why key and value, and why not just `{"headers":{"accept-datatime":"2017-03-11T17:00:00.000Z"}}`?

2017-10-06 11:32 UTC, pietercolpaert requested changes
Before merge, I’d still like to see these comments addressed

2017-10-06 11:32 UTC, pietercolpaert commented on lib/BrowserHttpFetcher.js
> +function HttpFetcher(accept, customHeaders) {
we should also have maxParallel en enableCache as properties to have the same interface outside of the browser

2017-10-06 11:32 UTC, pietercolpaert commented on README.md
> +var fetch = new ldfetch(options);
Good idea to put default headers in ldfetch itself!

2017-10-06 11:32 UTC, pietercolpaert commented on README.md
>  fetch.get(url).then(response => {
yet we should also be able to support  `fetch.get(url, options)`

2017-10-06 11:32 UTC, pietercolpaert commented on lib/NodeHttpFetcher.js
> -  this._enableCache = enableCache || true;
what’s happening here? Why do you always enable cache?

2017-11-04 15:57 UTC, merged

2017-11-04 15:57 UTC, pietercolpaert commented
Thanks!